// <auto-generated />
using AgenciaForest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenciaForest.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AgenciaForest.Models.CadastrarPassagem", b =>
                {
                    b.Property<int>("IdPassagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPassagem"), 1L, 1);

                    b.Property<string>("DestinoPassagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorPassagem")
                        .HasColumnType("float");

                    b.HasKey("IdPassagem");

                    b.ToTable("CadastrarPassagem");
                });

            modelBuilder.Entity("AgenciaForest.Models.ComprarPassagem", b =>
                {
                    b.Property<int>("IdPassagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPassagem"), 1L, 1);

                    b.Property<string>("DestinoPassagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorPassagem")
                        .HasColumnType("float");

                    b.Property<int>("cadastrarPassagem")
                        .HasColumnType("int");

                    b.HasKey("IdPassagem");

                    b.HasIndex("cadastrarPassagem");

                    b.ToTable("ComprarPassagem");
                });

            modelBuilder.Entity("AgenciaForest.Models.ComprarPassagem", b =>
                {
                    b.HasOne("AgenciaForest.Models.CadastrarPassagem", "CadastrarPassagem")
                        .WithMany()
                        .HasForeignKey("cadastrarPassagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CadastrarPassagem");
                });
#pragma warning restore 612, 618
        }
    }
}
